export const BUSINESS_INFO = {
  brandName: 'MasterFlow',
  legalName: 'RETTER Schluesseldienst & Hausmeisterservice',
  owner: 'Yevhenii Lementarchuk',
  street: 'Oertzenweg 46',
  postalCode: '14163',
  city: 'Berlin',
  country: 'Deutschland',
  phone: '+49 175 5328 410',
  email: 'info@berlin-retter.de',
  website: 'https://berlin-retter.de',
  vatNote: 'Als Kleinunternehmer gemaess Paragraf 19 Abs. 1 UStG wird keine Umsatzsteuer ausgewiesen.',
  supervisoryAuthority: 'Berliner Beauftragte fuer Datenschutz und Informationsfreiheit',
  supervisoryAuthorityUrl: 'https://www.datenschutz-berlin.de/',
} as const;
