export const BUSINESS_INFO = {
  brandName: 'MasterFlow',
  legalName: 'RETTER Schlüsseldienst & Hausmeisterservice',
  owner: 'Yevhenii Lementarchuk',
  street: 'Oertzenweg 46',
  postalCode: '14163',
  city: 'Berlin',
  country: 'Deutschland',
  phone: '+49 175 5328 410',
  email: 'info@berlin-retter.de',
  website: 'https://berlin-retter.de',
  taxNumber: '25/417/00339' ,
  vatNote: 'Als Kleinunternehmer gemäß § 19 Abs.\u00a01 UStG wird keine Umsatzsteuer ausgewiesen.',
  supervisoryAuthority: 'Berliner Beauftragte für Datenschutz und Informationsfreiheit',
  supervisoryAuthorityUrl: 'https://www.datenschutz-berlin.de/',
} as const;
